---
- name: Converge
  hosts: all
  tasks:
    - name: Update APT
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: "Include incron_role"
      include_role:
        name: "incron_role"
