---
# This is an example playbook to execute Ansible tests.


- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: "gather list of installed packages"
      package_facts:
        manager: "auto"
    - name: "incron package installed"
      assert:
        that: "'incron' in ansible_facts.packages"
